### PR TITLE
fix: return digest from attestation state save for OCC support

### LINKED ISSUE #2908: fix: remote attestation state writes fail on second save during initialization
## Problem

When the attestation crafter performs multiple state saves during initialization (e.g., running collectors that each update state), the second save fails with an OCC (Optimistic Concurrency Control) conflict.

The root cause is that `AttestationStateServiceSaveResponse` did not return the digest of the newly saved state. After a successful save, the client's `UpdateCheckSum` remained stale, so the next write sent an outdated `base_digest` that no longer matched the server-side state.

```
attestation_id=$(chainloop attestation init --workflow ${CHAINLOOP_WORKFLOW_NAME} --project ${CHAINLOOP_PROJECT_NAME} --release --remote-state -o json | jq -r .attestationID)
INF discovered AI agent config files agent=claude files=11
INF uploading ai-agent-config-claude-3801167160.json - sha256:f8e8a2449ae98ccc676de3dc6b41d0c3ee24e28ea7da8b3ad990df5f508ae827
INF successfully collected AI agent configuration agent=claude
ERR retrying in 652.072141ms error="evaluating attestation policies: failed to persist crafting state: failed to save state: rpc error: code = Aborted desc = saving attestation: failed to save attestation state: the provided base digest doesn't match the stored state, it might have changed, got=\"16b1ddff286db369d3256bb23b1ad1e7acf7954f2f88f07b2108861674692421\", want=\"e44e6cc538cf4e6010758567460080745c1393d60f28b3374f6b7666ed875b09\""
INF discovered AI agent config files agent=claude files=11
INF uploading ai-agent-config-claude-4821673.json - sha256:7490d637cef40c2f608f620aa5c7f58b5a9255fe48086e9433b33a3ed30b2400
INF successfully collected AI agent configuration agent=claude
INF discovered AI agent config files agent=claude files=11
INF uploading ai-agent-config-claude-365014333.json - sha256:c828347c1382cf90b75fcf140486275b5c147c5dcaea83e55a9c0ceacfc583d9
WRN collector failed error="adding AI agent config material for claude: failed to persist crafting state: failed to save state: rpc error: code = Aborted desc = saving attestation: failed to save attestation state: the provided base digest doesn't match the stored state, it might have changed, got=\"bfc6193105731b17a746772ec06df20454c64e701b7bd4cd2fc07cf76e355b55\", want=\"1fe2fccd9d55519460d56997f01e7ab618f56d05e87181c17f65314895a2a054\"" collector=ai-agent-config
ERR retrying in 677.93603ms error="evaluating attestation policies: failed to persist crafting state: failed to save state: rpc error: code = Aborted desc = saving attestation: failed to save attestation state: the provided base digest doesn't match the stored state, it might have changed, got=\"bfc6193105731b17a746772ec06df20454c64e701b7bd4cd2fc07cf76e355b55\", want=\"1fe2fccd9d55519460d56997f01e7ab618f56d05e87181c17f65314895a2a054\""
INF discovered AI agent config files agent=claude files=11
```

### PR DESCRIPTION
**Pull request by migmartri**
## Summary

- Return the newly computed digest in `AttestationStateServiceSaveResponse` so the remote state manager can track the current server-side state
- Fixes consecutive remote state writes failing with OCC conflict errors during attestation initialization (e.g., when multiple collectors update state sequentially)
- Move digest computation outside the database transaction to reduce transaction hold time

```
go run app/cli/main.go --insecure att init --workflow foo --project bar --collectors aiconfig --replace  -y --remote-state
WRN API contacted in insecure mode
Collecting PR metadata
INF detected PR/MR context number=123 platform=github
WRN collector failed error="adding PR/MR metadata material: crafting material: PR info validation failed: jsonschema: '/url' does not validate with https://schemas.chainloop.dev/prinfo/1.1/pr-info.schema.json#/properties/url/format: '' is not valid 'uri'" collector=pr-metadata
INF discovered AI agent config files agent=claude files=7
INF uploading ai-agent-config-claude-1403254423.json - sha256:9a4432bb81d323feea47eeda5483178f7c9e58effe56458cfcd96b6070e4bc60
INF successfully collected AI agent configuration agent=claude
INF Attestation initialized! now you can check its status or add materials to it
┌───────────────────────────┬──────────────────────────────────────┐
│ Initialized At            │ 21 Mar 26 15:05 UTC                  │
├───────────────────────────┼──────────────────────────────────────┤
│ Attestation ID            │ 396bb7a3-2654-4353-ad00-d69449c0e1cb │
│ Organization              │ mgiuel                               │
│ Name                      │ foo                                  │
│ Project                   │ bar                                  │
│ Version                   │ v1.83.0+next (prerelease)            │
│ Contract                  │ bar-foo (revision 1)                 │
│ Policy violation strategy │ ADVISORY                             │
└───────────────────────────┴──────────────────────────────────────┘
┌───────────────────────────────────────────────────────────────────────────────────────┐
│ Materials                                                                             │
├─────────────┬─────────────────────────────────────────────────────────────────────────┤
│ Name        │ ai-agent-config-claude                                                  │
│ Type        │ CHAINLOOP_AI_AGENT_CONFIG                                               │
│ Set         │ Yes                                                                     │
│ Required    │ No                                                                      │
│ Value       │ ai-agent-config-claude-1403254423.json                                  │
│ Digest      │ sha256:9a4432bb81d323feea47eeda5483178f7c9e58effe56458cfcd96b6070e4bc60 │
│ Annotations │ ------                                                                  │
│             │ chainloop.material.size: 50566                                          │
│             │ chainloop.material.aiagent.name: claude                                 │
└─────────────┴─────────────────────────────────────────────────────────────────────────┘
```

Fixes #2908

### CODE REVIEW

File: app/controlplane/pkg/biz/attestationstate.go [hunk 1]
```diff
@@ -39,7 +39,7 @@ type AttestationState struct {
 
 type AttestationStateRepo interface {
 	Initialized(ctx context.Context, workflowRunID uuid.UUID) (bool, error)
-	Save(ctx context.Context, workflowRunID uuid.UUID, state []byte, baseDigest string) error
+	Save(ctx context.Context, workflowRunID uuid.UUID, state []byte, baseDigest string) (string, error)
```
Comment (migmartri) [inline app/controlplane/pkg/biz/attestationstate.go:42]: this is the intersting bit

File: pkg/attestation/crafter/statemanager/remote/remote.go [hunk 2]
```diff
@@ -67,10 +67,14 @@ func (r *Remote) Write(ctx context.Context, key string, state *crafter.Versioned
...
 
 	r.logger.Debug().Str("key", key).Str("baseDigest", state.UpdateCheckSum).Msg("Writing state to remote")
-	if _, err := r.client.Save(ctx, &pb.AttestationStateServiceSaveRequest{WorkflowRunId: key, AttestationState: state.CraftingState, BaseDigest: state.UpdateCheckSum}); err != nil {
+	resp, err := r.client.Save(ctx, &pb.AttestationStateServiceSaveRequest{WorkflowRunId: key, AttestationState: state.CraftingState, BaseDigest: state.UpdateCheckSum})
+	if err != nil {
 		return fmt.Errorf("failed to save state: %w", err)
 	}
 
+	// Update the checksum so subsequent writes use the correct base digest
+	state.UpdateCheckSum = resp.GetDigest()
```
Comment (migmartri) [inline pkg/attestation/crafter/statemanager/remote/remote.go]: and this is the key, now the local state after writing has the updated checksum so it doesn't need to load it again

File: pkg/attestation/crafter/crafter.go [hunk 3]
```diff
@@ -147,11 +147,22 @@ func (c *Crafter) RunCollectors(ctx context.Context, attestationID string, casBa
...
 	for _, collector := range c.collectors {
 		if err := collector.Collect(ctx, c, attestationID, casBackend); err != nil {
 			c.Logger.Warn().Err(err).Str("collector", collector.ID()).Msg("collector failed")
 		}
 	}
+
+	// Reload state if collectors modified it and the local digest may be stale.
+	// When the digest changed, writes happened but we can't be sure the checksum
+	// reflects the true server-side state (e.g. old servers don't return digests).
+	if c.CraftingState.UpdateCheckSum != digestBeforeCollectors {
```
Comment (migmartri) [inline pkg/attestation/crafter/crafter.go:162]: @jiparis technically the problem could be fixed by just adding this code. But I've added a better mechanism for new servers that refresh the just updated digest.

Returning and updating the digest also fixes the problem, but only for new servers
