### PR TITLE
fix(attestation): generic normalization function

### LINKED ISSUE #365: panic at attestation push
```
chainloop attestation push --key env://CHAINLOOP_SIGNING_KEY 2>&1 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xd3d099]

goroutine 1 [running]:
github.com/chainloop-dev/chainloop/internal/attestation/renderer/chainloop.outputMaterials(0xc0001662a0, 0x1)
	/home/runner/work/chainloop/chainloop/internal/attestation/renderer/chainloop/v02.go:119 +0x2b9
github.com/chainloop-dev/chainloop/internal/attestation/renderer/chainloop.(*RendererV02).Header(0xc000116c[4](https://github.com/chainloop-dev/spring-petclinic/actions/runs/6332060606/job/17197920332#step:8:4)0)
	/home/runner/work/chainloop/chainloop/internal/attestation/renderer/chainloop/v02.go:74 +0x233
github.com/chainloop-dev/chainloop/internal/attestation/renderer.(*AttestationRenderer).statement(0xc000289f40)
	/home/runner/work/chainloop/chainloop/internal/attestation/renderer/renderer.go:11[5](https://github.com/chainloop-dev/spring-petclinic/actions/runs/6332060606/job/17197920332#step:8:5) +0x2e
github.com/chainloop-dev/chainloop/internal/attestation/renderer.(*AttestationRenderer).Render(0xc000289f40)
	/home/runner/work/chainloop/chainloop/internal/attestation/renderer/renderer.go:82 +0x52
github.com/chainloop-dev/chainloop/app/cli/internal/action.(*AttestationPush).Run(0xc0008bea40, 0x0?)
	/home/runner/work/chainloop/chainloop/app/cli/internal/action/attestation_push.go:115 +0x[6](https://github.com/chainloop-dev/spring-petclinic/actions/runs/6332060606/job/17197920332#step:8:6)85
github.com/chainloop-dev/chainloop/app/cli/cmd.newAttestationPushCmd.func2(0xc000[7](https://github.com/chainloop-dev/spring-petclinic/actions/runs/6332060606/job/17197920332#step:8:7)90f00?, {0x219cadd?, 0x4?, 0x219c9f5?})
	/home/runner/work/chainloop/chainloop/app/cli/cmd/attestation_push.go:73 +0x13b
github.com/spf13/cobra.(*Command).execute(0xc000790f00, {0xc00040ca00, 0x2, 0x2})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:940 +0x[8](https://github.com/chainloop-dev/spring-petclinic/actions/runs/6332060606/job/17197920332#step:8:8)7c
github.com/spf[13](https://github.com/chainloop-dev/spring-petclinic/actions/runs/6332060606/job/17197920332#step:8:13)/cobra.(*Command).ExecuteC(0xc0000acc00)
```

### PR DESCRIPTION
**Pull request by migmartri**
Fixes #365

The issue was that we had a hardcoded list of material types to normalize and it was outside of the testing loop.

The issue was consistent when an user tried to use any new material type, such as the new `sarif` or `vex` types.

This code makes two things

- Change the normalization code to be less brittle and dynamic based on the structure of the material type
- Adds missing error handling

Example of successful attestation

```
┌────────────────────────────────────────────────────────────────────────────────────┐
│ Materials                                                                          │
├──────────┬─────────────────────────────────────────────────────────────────────────┤
│ Name     │ image                                                                   │
│ Type     │ CONTAINER_IMAGE                                                         │
│ Digest   │ sha256:39d48595c363755c9e00240ea74e0b6be0b5bdfb63ef2e58b9ec469e8828787d │
├──────────┼─────────────────────────────────────────────────────────────────────────┤
│ Name     │ rootfs                                                                  │
│ Type     │ ARTIFACT                                                                │
│ Filename │ sbom.cyclonedx.json                                                     │
│ Value    │                                                                         │
│ Digest   │ sha256:16159bb881eb4ab7eb5d8afc5350b0feeed1e31c0a268e355e74f9ccbe885e0c │
├──────────┼─────────────────────────────────────────────────────────────────────────┤
│ Name     │ sarif                                                                   │
│ Type     │ SARIF                                                                   │
│ Filename │ report.sarif                                                            │
│ Value    │                                                                         │
│ Digest   │ sha256:c4a63494f9289dd9fd44f841efb4f5b52765c2de6332f2d86e5f6c0340b40a95 │
├──────────┼─────────────────────────────────────────────────────────────────────────┤
│ Name     │ sbom                                                                    │
│ Type     │ SBOM_CYCLONEDX_JSON                                                     │
│ Filename │ sbom.cyclonedx.json                                                     │
│ Value    │                                                                         │
│ Digest   │ sha256:16159bb881eb4ab7eb5d8afc5350b0feeed1e31c0a268e355e74f9ccbe885e0c │
├──────────┼─────────────────────────────────────────────────────────────────────────┤
│ Name     │ vex                                                                     │
│ Type     │ OPENVEX                                                                 │
│ Filename │ openvex_v0.2.0.json                                                     │
│ Value    │                                                                         │
│ Digest   │ sha256:b4bd86d5855f94bcac0a92d3100ae7b85d050bd2e5fb9037a200e5f5f0b073a2 │
└──────────┴─────────────────────────────────────────────────────────────────────────┘

```

### CODE REVIEW

File: internal/attestation/renderer/chainloop/v01.go [hunk 1]
```diff
@@ -116,7 +116,10 @@ func outputChainloopMaterials(att *v1.Attestation, onlyOutput bool) []*Provenanc
 		mdef := materials[mdefName]
 
 		artifactType := mdef.MaterialType
-		nMaterial := mdef.NormalizedOutput()
+		nMaterial, err := mdef.NormalizedOutput()
+		if err != nil {
```
Comment (danlishka) [inline internal/attestation/renderer/chainloop/v01.go:120]: why do we continue on error, can you add a comment here?

**Review by danlishka — APPROVED** [review]
LGTM

File: internal/attestation/renderer/chainloop/v01.go (hunk 1 above)
Comment (migmartri) [reply internal/attestation/renderer/chainloop/v01.go:120]: because v01 is actually deprecated and in fact we should probably remove it. Just to not to add more code.

Comment (migmartri) [reply internal/attestation/renderer/chainloop/v01.go:120]: I should have added a comment on the reasoning, sorry.
