### PR TITLE
fix(authZ): propagate new policies across replicas

### LINKED ISSUE #483: bug(authz): policies are not propagated across all the controlplane instances
casbin enforcers are initialized in each instance of the controlplane, and these are backed by a common DB table.

Although they share that DB it seems that `enforcer.Enforce` is not being refreshed with the value in the DB. So for example, if some policies are created by the replica `a`, these policies will not be available to replica `b` until a restart.

### PR DESCRIPTION
**Pull request by migmartri**
Adds a watcher that triggers the reload of the policies when any other casbin replica has injected/removed a policy in the DB. 

Fixes #483 

cc/ @fgallina

### CODE REVIEW

File: app/controlplane/internal/authz/authz_test.go [hunk 1]
```diff
@@ -160,13 +164,68 @@ func TestClearPolicies(t *testing.T) {
...
 		require.FailNow(t, err.Error())
 	}
 
-	enforcer, err := NewFiletypeEnforcer(f.Name())
+	enforcer, err := authz.NewFiletypeEnforcer(f.Name())
 	require.NoError(t, err)
 	return enforcer, f
 }
+
+func TestMultiReplicaPropagation(t *testing.T) {
```
Comment (migmartri) [inline app/controlplane/internal/authz/authz_test.go:178]: This is the test that handles propagation

**Review by danlishka — APPROVED** [review]
LGTM
