### PR TITLE
fix(contracts): Add missing project eager loading

### LINKED ISSUE #2045: wrong output, missing workflow name in associated workflows
```
 chainloop wf contract update --name myproject-build-container-image --contract https://raw.githubusercontent.com/chainloop-dev/chainloop/refs/heads/main/docs/examples/quickstart/contract-only-materials.yaml
INF Contract updated!
┌────────────────────────────────────────────────────────┐
│ Contract                                               │
├──────────────────────┬─────────────────────────────────┤
│ Name                 │ myproject-build-container-image │
├──────────────────────┼─────────────────────────────────┤
│ Description          │                                 │
├──────────────────────┼─────────────────────────────────┤
│ Associated Workflows │ myproject/                      │
├──────────────────────┼─────────────────────────────────┤
│ Revision number      │ 2                               │
├──────────────────────┼─────────────────────────────────┤
│ Revision Created At  │ 14 May 25 12:21 UTC             │
└──────────────────────┴─────────────────────────────────┘
┌──────────────────────────────────┐
│ schemaVersion: v1                │
│ materials:                       │
│   - name: container              │
│     type: CONTAINER_IMAGE        │
│   - name: sbom                   │
│     type: SBOM_CYCLONEDX_JSON    │
│   - name: vulnerabilities-report │
│     type: SARIF                  │
└──────────────────────────────────┘
```

### PR DESCRIPTION
**Pull request by javirln**
This patch queries for missing filds and eager loads projects when looking to load the workflow reference in the context of a contract.

The project name gets loaded correctly for the `describe`:
```
$ chainloop wf contract describe --name core-containers-sbom
WRN API contacted in insecure mode
INF To download the contract, run the command with the "--output schema" option
┌─────────────────────────────────────────────┐
│ Contract                                    │
├──────────────────────┬──────────────────────┤
│ Name                 │ core-containers-sbom │
├──────────────────────┼──────────────────────┤
│ Description          │                      │
├──────────────────────┼──────────────────────┤
│ Associated Workflows │ core/containers-sbom │
├──────────────────────┼──────────────────────┤
│ Revision number      │ 4                    │
├──────────────────────┼──────────────────────┤
│ Revision Created At  │ 13 May 25 14:26 UTC  │
└──────────────────────┴──────────────────────┘
```

For the `update`:
```
❯ chainloop --insecure wf contract update --name myproject-build-container-image --contract https://raw.githubusercontent.com/chainloop-dev/chainloop/refs/heads/main/docs/examples/quickstart/contract-only-materials.yaml
WRN API contacted in insecure mode
INF Contract updated!
┌────────────────────────────────────────────────────────┐
│ Contract                                               │
├──────────────────────┬─────────────────────────────────┤
│ Name                 │ myproject-build-container-image │
├──────────────────────┼─────────────────────────────────┤
│ Description          │                                 │
├──────────────────────┼─────────────────────────────────┤
│ Associated Workflows │ core/build                      │
├──────────────────────┼─────────────────────────────────┤
│ Revision number      │ 1                               │
├──────────────────────┼─────────────────────────────────┤
│ Revision Created At  │ 15 May 25 06:50 UTC             │
└──────────────────────┴─────────────────────────────────┘
┌──────────────────────────────────┐
│ schemaVersion: v1                │
│ materials:                       │
│   - name: container              │
│     type: CONTAINER_IMAGE        │
│   - name: sbom                   │
│     type: SBOM_CYCLONEDX_JSON    │
│   - name: vulnerabilities-report │
│     type: SARIF                  │
└──────────────────────────────────┘
```

Close #2045

### CODE REVIEW

File: app/controlplane/pkg/data/workflowcontract.go [hunk 1]
```diff
@@ -372,7 +372,7 @@ func contractInOrgQuery(ctx context.Context, q *ent.OrganizationQuery, orgID uui
 
 	if !c.SkipGetReferences {
 		query = query.WithWorkflows(func(q *ent.WorkflowQuery) {
-			q.Where(workflow.DeletedAtIsNil())
+			q.Where(workflow.DeletedAtIsNil()).WithProject()
```
Comment (javirln) [inline app/controlplane/pkg/data/workflowcontract.go:375]: This fixes `wf contract describe`

File: app/controlplane/pkg/data/workflowcontract.go [hunk 2]
```diff
@@ -406,9 +406,11 @@ func getWorkflowReferences(ctx context.Context, schema *ent.WorkflowContract) ([
...
 	if workflows == nil {
 		var err error
-		workflows, err = schema.QueryWorkflows().WithProject().
-			Where(workflow.DeletedAtIsNil()).WithProject().
-			Select(workflowcontract.FieldID).All(ctx)
+		workflows, err = schema.QueryWorkflows().
+			Where(workflow.DeletedAtIsNil()).
+			WithProject().
+			Select(workflow.FieldID, workflow.FieldName).
+			All(ctx)
```
Comment (javirln) [inline app/controlplane/pkg/data/workflowcontract.go:413]: This fixes `wf contract update`

File: app/controlplane/pkg/data/workflowcontract.go (hunk 1 above)
Comment (migmartri) [reply app/controlplane/pkg/data/workflowcontract.go:375]: I think we removed this because the inner query was very expensive during the attestation process. We might want to do it more surgically.

File: app/controlplane/pkg/data/workflowcontract.go [hunk 3]
```diff
@@ -372,7 +374,7 @@ func contractInOrgQuery(ctx context.Context, q *ent.OrganizationQuery, orgID uui
 
 	if !c.SkipGetReferences {
 		query = query.WithWorkflows(func(q *ent.WorkflowQuery) {
-			q.Where(workflow.DeletedAtIsNil())
+			q.Where(workflow.DeletedAtIsNil()).WithProject().Select(project.FieldID, project.FieldName)
```
Comment (javirln) [inline app/controlplane/pkg/data/workflowcontract.go:377]: I was checking the code and I think it's ok. The `SkipGetReferences` flag already controls whether references are fetched, and when they’re not needed, the fetch is skipped. My reasoning is that projects are part of the reference itself and are always required. To optimize it, let's query the fields necessary to build the reference.

**Review by jiparis — APPROVED** [review]
