### PR TITLE
fix(policy-devel): add policy spec validation errors

### LINKED ISSUE #2388: Add policy spec validation errors to lint
Validations errors were removed in the previous change.

### PR DESCRIPTION
**Pull request by Piskoo**
This PR reintroduces policy spec validation errors that were removed in previous change.

Closes #2388

### CODE REVIEW

**Comment by Piskoo** [comment]
Errors were mistakenly removed, added #2390 to avoid that in the future

File: app/cli/internal/policydevel/lint.go [hunk 1]
```diff
@@ -128,7 +128,7 @@ func (p *PolicyToLint) loadReferencedRegoFiles(baseDir string) error {
 	for _, yamlFile := range p.YAMLFiles {
 		var parsed v1.Policy
 		if err := unmarshal.FromRaw(yamlFile.Content, unmarshal.RawFormatYAML, &parsed, true); err != nil {
-			// Ignore parse errors here; they'll be caught in validation
+			p.AddError(yamlFile.Path, err.Error(), 0)
```
Comment (migmartri) [inline app/cli/internal/policydevel/lint.go:131]: is this including protovalidate errors?

Comment (Piskoo) [reply app/cli/internal/policydevel/lint.go:131]: Yes
